---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cluster-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "batch", "policy", "rbac.authorization.k8s.io", "autoscaling", "apiextensions.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "persistentvolumes", "events", "secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "roles", "rolebindings", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd-cluster
roleRef:
  kind: ClusterRole
  name: argocd-cluster-role
  apiGroup: rbac.authorization.k8s.io
